### ISSUE TITLE
Hide cropped scrollbar more thoroughly with css props

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/snapper#68]
These will more robustly hide it

```css
.snapper-enhanced .snapper_pane_crop .snapper_pane,
.enhanced .snapper_pane_crop .snapper_pane {
  /* IE and edge */
	-ms-overflow-style: -ms-autohiding-scrollbar;
	/* Firefox */
	scrollbar-width: none;
}
.snapper-enhanced .snapper_pane_crop .snapper_pane::-webkit-scrollbar,
.enhanced .snapper_pane_crop .snapper_pane::-webkit-scrollbar {
	display: none;
}
```

Note: keying off the pane_crop here since that's there only when hiding is desired.
